### PR TITLE
Update ifdhandler.c: wrong select protocol

### PR DESCRIPTION
**Pull request by DimkaM**
wrong select protocol

### CODE REVIEW

**Comment by DimkaM** [comment]
T0 does not use bit 4.
With bit 4 == 1, the card generates an error.

Datasheet:
For T=0 ,B0 – 0b, B7-2 – 000000bB1 – Convention used (b1=0 for direct, b1=1 forinverse)

**Comment by LudovicRousseau** [comment]
What is your "Datasheet"?
Do you have the reference to ISO 7816-3 that document this part?

**Comment by DimkaM** [comment]
> What is your "Datasheet"? Do you have the reference to ISO 7816-3 that document this part?

The bmTCCKST0 field on page 33 in https://www.usb.org/sites/default/files/DWG_Smart-Card_CCID_Rev110.pdf

**Comment by DimkaM** [comment]
> T0 does not use bit 4. With bit 4 == 1, the card generates an error.
> 
> Datasheet: For T=0 ,B0 – 0b, B7-2 – 000000bB1 – Convention used (b1=0 for direct, b1=1 forinverse)

without a patch returns an error:
#define SCARD_E_NOT_TRANSACTED _HRESULT_TYPEDEF_(0x80100016L)

**Comment by LudovicRousseau** [comment]
The `bmTCCKST0` field is set at https://github.com/LudovicRousseau/CCID/blob/master/src/ifdhandler.c#L1136

Your problem is different. Please provide a complete trace as described in https://ccid.apdu.fr/#support
It will help if you generates 2 traces: one with the current code, and one with your patch applied.

**Comment by DimkaM** [comment]
> The `bmTCCKST0` field is set at https://github.com/LudovicRousseau/CCID/blob/master/src/ifdhandler.c#L1136
> 
> Your problem is different. Please provide a complete trace as described in https://ccid.apdu.fr/#support It will help if you generates 2 traces: one with the current code, and one with your patch applied.

I made and attached logs

[log_error.txt](https://github.com/LudovicRousseau/CCID/files/11914986/log_error.txt)
[log_ok.txt](https://github.com/LudovicRousseau/CCID/files/11914987/log_ok.txt)

**Comment by DimkaM** [comment]
I'm sorry.
Here are the logs from the latest source codes.
We have modified ccid_serial.c and commands.c to support AK9564 reader, there may be a bug in our code.
[log_bad.txt](https://github.com/LudovicRousseau/CCID/files/11917746/log_bad.txt)
[log_good.txt](https://github.com/LudovicRousseau/CCID/files/11917747/log_good.txt)

**Comment by LudovicRousseau** [comment]
I can't support a driver you have modified.
But feel free to use this patch if is works for you.

**Pull request closed without merging**
